
-- What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue 
FROM customer_shopping_analysis
GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount 
FROM customer_shopping_analysis 
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_shopping_analysis);


-- Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS average_product_rating
FROM customer_shopping_analysis
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer_shopping_analysis 
WHERE shipping_type IN ('Standard', 'Express') 
GROUP BY shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
       COUNT(customer_id) AS total_customers, 
       ROUND(AVG(purchase_amount), 2) AS average_spend, 
       ROUND(SUM(purchase_amount),2) AS total_revenue 
FROM customer_shopping_analysis  
GROUP BY subscription_status 
ORDER BY total_revenue, average_spend DESC;


-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
       ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_rate 
FROM customer_shopping_analysis   
GROUP BY item_purchased 
ORDER BY discount_rate DESC 
LIMIT 5;


-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases. Show the count of each segment.
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases <= 5 THEN 'New'
            WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping_analysis
)

SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers DESC;


-- What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_shopping_analysis
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders 
FROM item_counts 
WHERE item_rank <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers 
FROM customer_shopping_analysis 
WHERE previous_purchases > 5 
GROUP BY subscription_status;

-- What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue 
FROM customer_shopping_analysis 
GROUP BY age_group 
ORDER BY total_revenue DESC;

-- Which state generates the highest revenue?
SELECT location,
       SUM(purchase_amount) AS total_revenue
FROM customer_shopping_analysis
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;

-- Which season contributes the most sales revenue?
SELECT season,
       SUM(purchase_amount) AS total_revenue
FROM customer_shopping_analysis
GROUP BY season
ORDER BY total_revenue DESC;


-- What is the most preferred payment method?
SELECT payment_method,
       COUNT(*) AS total_transactions
FROM customer_shopping_analysis
GROUP BY payment_method
ORDER BY total_transactions DESC;


-- Which age group spends the most on average?
SELECT age_group,
       ROUND(AVG(purchase_amount),2) AS avg_spending
FROM customer_shopping_analysis
GROUP BY age_group
ORDER BY avg_spending DESC;


-- Do higher review ratings lead to higher purchase amounts?
SELECT review_rating,
       ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer_shopping_analysis
GROUP BY review_rating
ORDER BY review_rating;


-- Which subscription status has the highest average review rating?
SELECT subscription_status,
       ROUND(AVG(review_rating),2) AS avg_rating
FROM customer_shopping_analysis
GROUP BY subscription_status
ORDER BY avg_rating DESC;


-- Which shipping type is most preferred by customers?
SELECT shipping_type,
       COUNT(*) AS total_orders
FROM customer_shopping_analysis
GROUP BY shipping_type
ORDER BY total_orders DESC;


-- What is the average purchase frequency for subscribers vs non-subscribers?
SELECT subscription_status,
       ROUND(AVG(CAST(purchase_frequency_days AS DECIMAL(10,2))),2) AS avg_days_between_purchases
FROM customer_shopping_analysis
GROUP BY subscription_status;


-- Which category generates the highest revenue per customer?
SELECT category,
       ROUND(
           SUM(purchase_amount) / COUNT(DISTINCT customer_id),
           2
       ) AS revenue_per_customer
FROM customer_shopping_analysis
GROUP BY category
ORDER BY revenue_per_customer DESC;


-- Who are the top 10 highest-spending customers?
SELECT customer_id,
       SUM(purchase_amount) AS total_spent
FROM customer_shopping_analysis
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;



